#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PUBLIC_FOLDER="/public"

IFS=' ' read -a ARGUMENTS_ARRAY <<< "$@"

#if no arguments are passed in
if [ $# == 0 ]
  then
    java -jar ../../build/jar/server.jar -p 5000 -d $DIR$PUBLIC_FOLDER &echo $! > ./program.pid
fi

#if arguments are passed in, we need to check the public directory
if [ $# != 0 ]
  then
    #if the public folder is the relative folder
    if [ ${ARGUMENTS_ARRAY[3]} == "/public" ]
      then
        java -jar ../../build/jar/server.jar ${ARGUMENTS_ARRAY[0]} ${ARGUMENTS_ARRAY[1]} ${ARGUMENTS_ARRAY[2]} $DIR$PUBLIC_FOLDER &echo $! > ./program.pid
    fi
    #if arguments are passed in and the public folder is the full path to the public folder
    if [ ${ARGUMENTS_ARRAY[3]} != "/public" ]
      then
        java -jar ../../build/jar/server.jar "$@" &echo $! > ./program.pid
    fi
fi